analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.6783029
  brandStrength: 0.2389903
  lightness: 0.2873254
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  rhythmicContrast: 0.7030075
typography_spectrum: 0.4688507
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9382384
favicon: null
name: Unicoder
